Welcome page
NexArb/WebApp pull request #12
Opened 2023-11-13 10:04 UTC by kihlaj

**What is done:**

- [X] Feature added
- [ ] Bug fixed
- [ ] Code refactored
- [ ] Documentation updated
- [ ] Tests added
- [ ] Other (please specify):

### PR Purpose

2023-11-13 12:39 UTC, DogukanGun commented
Could u solve the conflicts?

2023-11-13 14:54 UTC, kihlaj commented
Should I merge with main?

2023-11-13 15:08 UTC, DogukanGun commented
> Should I merge with main?

Yes, you should merge with main and then solve your conflicts in your local environment. After that please push your code again.

2023-11-14 14:23 UTC, DogukanGun requested changes

2023-11-14 14:23 UTC, DogukanGun commented on .github/auto_assign.yml
> +reviewers:
Please revert the changes in .github file

2023-11-14 14:23 UTC, DogukanGun commented on .github/pull_request_template.md
> +### PR Purpose
Please revert the changes in .github file

2023-11-14 14:23 UTC, DogukanGun commented on .github/workflows/auto-assign.yml
> +      - name: 'Auto-assign issue'
Please revert the changes in .github file

2023-11-14 14:23 UTC, DogukanGun commented on .github/workflows/eslint.yml
> +    branches: ['main']
Please revert the changes in .github file

2023-11-14 14:23 UTC, DogukanGun commented on .github/workflows/eslint.yml
> +    branches: ['main']
Please revert the changes in .github file

2023-11-14 14:23 UTC, DogukanGun commented on .github/workflows/pull-request.yml
>      steps:
Please revert the changes in .github file

2023-11-14 14:23 UTC, DogukanGun commented on app/globals.css
> +@layer utilities {
This might be done in tailwind classes, could u check ?

2023-11-14 14:23 UTC, DogukanGun commented on components/CustomTextfield/Contact.tsx
> +          name="name"
Could u make this a component?

2023-11-14 14:23 UTC, DogukanGun commented on components/CustomTextfield/Contact.tsx
> +      <form className="flex h-[624.04px] w-[514.56px] flex-col rounded-[10px] bg-white p-12">
Could u change `h-[624.04px] w-[514.56px] rounded-[10px]` ?  We should use values in tailwind predefined classes.

2023-11-14 14:23 UTC, DogukanGun commented on components/CustomFooter/index.tsx
> +                  <div className="flexCenter h-[35.70px] w-[35.70px] rounded-lg bg-white bg-opacity-20">
Could u change `h-[35.70px] w-[35.70px]` ? We should use values in tailwind predefined classes.

2023-11-14 14:23 UTC, DogukanGun commented on components/CustomFooter/index.tsx
> +                <div className="h-[85.39px] w-[275.89px] text-base font-normal leading-relaxed">
Could u change `h-[85.39px] w-[275.89px]` ? We should use values in tailwind predefined classes.

2023-11-14 14:23 UTC, DogukanGun commented on components/CustomFooter/index.tsx
> +              <div className="mt-8 h-[140.14px] w-[436.83px] text-[22px] font-medium leading-loose">
Please tailwind predefined classes.

2023-11-14 14:23 UTC, DogukanGun commented on components/CustomFooter/index.tsx
> +                <div className="h-[28.46px] w-[263.85px] text-base font-normal leading-relaxed">
Please tailwind predefined classes.

2023-11-14 14:23 UTC, DogukanGun commented on components/CustomFooter/index.tsx
> +              <div className="mt-14 text-[42px] font-bold leading-[52px]">
Please tailwind predefined classes.

2023-11-18 21:01 UTC, DogukanGun approved these changes

2023-11-18 21:03 UTC, merged